#!/bin/bash
if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <pcap_file_name> <csv_file_name>"
  echo "	tshark should be in system path"
  exit 1
fi

pcap_file_name=$1
csv_file_name=$2

tshark -r $pcap_file_name -T fields -e frame.number -e frame.time -e ip.src -e ip.dst -e ip.proto -e frame.len -e _ws.col.Info -E header=y -E separator=, -E quote=d -E occurrence=f > $csv_file_name
